### ISSUE TITLE
change yaml format to something else

### ISSUE THREAD

**Issue by yunhuige** [vvoelz/biceps#16]
We need to change from Yaml to some condensed format like Numpy to save time and lower the memory usage. Keep in mind, we don't need it to be human readable but it needs to be a dictionary format then it will still work with the MBAR and plot scripts. Also it will be good if we prepare some scripts that can convert it to a human readable format.

**Comment by yunhuige** [comment]
What candidates do we have now? Numpy? How about *.csv?

**Comment by robraddi** [comment]
hd5/h5  is another option. 
Didn't you mention a compressed filetype?

**Comment by yunhuige** [comment]
What is the status of your test? Do we have any conclusion yet? @robraddi

**Comment by robraddi** [comment]
We should keep YAML due to reasons I mentioned to you personally.

**Comment by yunhuige** [comment]
@robraddi I think I need to reopen this issue until we benchmark all different candidates. Maybe you can use the current example dataset but change it from 1000 steps to some bigger numbers and have a list of saving time and if applicable, memory required by sampling them use the current scripts?

**Comment by robraddi** [comment]
@yunhuige Okay, so I added a few methods on reading and writing various filetypes. Lets try to run some tests this week on a dataset to see how they compare.  : )

**Comment by robraddi** [comment]
Results from our extensive tests can be found in /BICePs2.0/tests/test_format
