### ISSUE TITLE
Come up with a logo design of BICePs

### ISSUE THREAD

**Issue by yunhuige** [vvoelz/biceps#41]
Artists, it's your show time!

**Comment by robraddi** [comment]
A Scintilla of Inspiration
--------------------------
I was told there might be a new course offered: CHEM5402 - Chemical Biology.  I followed up by checking out [the website](https://manhartlab.weebly.com/teaching.html) of the probable professor. She has created a cool logo using the 'Temple T' overlaying an image of a DNA strand next to a protein structure.

**Comment by vvoelz** [comment]
I had an artistic vision: https://drive.google.com/file/d/14KUX-K3GLWiGJXhxL8527SRSYC4RdW7D/view?usp=sharing

**Comment by robraddi** [comment]
![image](https://user-images.githubusercontent.com/25323809/126021639-27fd78dd-02f8-4529-872c-ee84bdd50fc0.png)
