### ISSUE TITLE
Compiling issues with tabs

### ISSUE THREAD

**Issue by robraddi** [vvoelz/biceps#43]
Here is an error I kept receiving when attempting to apply Cython to our python code:
**PosteriorSampler.pyx:166:0: Mixed use of tabs and spaces**
I fixed the issue, but it would be convenient if we didn't have to change tabs into spaces. 
Its not a big deal. Lets just try to remember to use spaces. 
Maybe there is a command that can be placed in your ~/.vimrc file that avoids this?

Compiling PosteriorSampler.pyx because it changed.
[1/1] Cythonizing PosteriorSampler.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        # frequency of storing trajectory samples
        self.traj_every = 100

        # initialze restraint child class
        r_J = R.restraint_J()
^
------------------------------------------------------------

**PosteriorSampler.pyx:166:0: Mixed use of tabs and spaces**
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    ext_modules = cythonize("PosteriorSampler.pyx")
  File "/Users/tuc41004/anaconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/Users/tuc41004/anaconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: PosteriorSampler.pyx

**Comment by robraddi** [comment]
This should've been an email... I'm closing this.

**Comment by yunhuige** [comment]
I know how to do it in my vimrc file and I have it in vav5 (our testing machine). I just didn't add it in all of my machines. I will do it when I'm in the lab and this won't be an issue in the future.
