### ISSUE TITLE
may need to fix in the future...

### ISSUE THREAD

**Issue by yunhuige** [vvoelz/biceps#49]
new_src/PosteriorSampler.py:469: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if self.results['allowed_gamma'] != None:

Solution could be replacing "!=" with "is not". Haven't tested yet.

**Comment by robraddi** [comment]
@yunhuige I believe that Python 3 requires this now.

**Comment by vvoelz** [comment]
Rob says this is done.
