### ISSUE TITLE
biceps.convergence module

### ISSUE THREAD

**Issue by vvoelz** [vvoelz/biceps#55]
There are a bunch of functions in `biceps/toolbox.py` to compute and analyze autocorrelation functions for convergence tests.   For now, I'm putting *copies* of these functions in a new `biceps.convergence` module.  Later we can remove these and scripts that use them.

**Comment by yunhuige** [comment]
Some of those functions are not necessary especially those plotting functions. Let me know your plan of how to finish this module. @vvoelz

**Comment by yunhuige** [comment]
I'm working on the scripts of this module. I will post you once I'm done. @vvoelz @robraddi

**Comment by yunhuige** [comment]
Python version and cpp version is done.
