### ISSUE TITLE
mini-biceps for training parameters in lnPF calculation

### ISSUE THREAD

**Issue by yunhuige** [vvoelz/biceps#65]
We should have a good tutorial/example of how we train our model to obtain the prior distribution of those 6 parameters. I remembered we once had a Jupiter notebook and it should be somewhere in the voelzlab repository. We need find it, run it, and add documents for the tutorial. People are very interested in this and I think it will be very helpful. Then add this to the manuscript if it can fit anywhere.

**Comment by vvoelz** [comment]
I told Davide I would pack up the scripts to do this, and put it in a notebook.   I should have some time to do it this week (?).  I plan to  create a branch that creates a `HDX-PF-forward-model` directory inside BICePs_2.0

**Comment by vvoelz** [comment]
Okay after hearing from Rob about all the new changes to `biceps`,  to avoid confusion I’m going to put the forward model posterior sampling scripts in a separate repo:  https://github.com/vvoelz/HDX-forward-model .   We can share with others that from that, and incorporate it later in `biceps`

**Comment by vvoelz** [comment]
Okay the https://github.com/vvoelz/HDX-forward-model  repo is ready to go, so I'm going to close up this thread
