### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [vvoelz/biceps#77]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2.0b4. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary biceps -w /tmp/ext biceps==2.0b4
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting biceps==2.0b4
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/8e6/987daf7bccf37/biceps-2.0b4.tar.gz (44 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-du2sf6qv/biceps/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-du2sf6qv/biceps/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-du2sf6qv/biceps/pip-egg-info
         cwd: /tmp/pip-wheel-du2sf6qv/biceps/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-du2sf6qv/biceps/setup.py", line 30, in <module>
        with open(path.join(here, '../README.md'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-du2sf6qv/biceps/../README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by robraddi** [comment]
@thatch thanks for the catch! Our team will be releasing the official version (in Python3) very soon. In the meantime, your best bet is to clone the repo.

**Comment by thatch** [comment]
I tried to submit a PR but can't test because `mdtraj` doesn't compile for me so I can't actually test.  Something like "include *.md" in MANIFEST.in should fix this.

**Comment by robraddi** [comment]
@thatch don't worry about that version. I'm currently pulling it from PyPi as it is a beta version for Python 2 and was meant for testing purposes. I didn't anticipate any interest since we haven't officially released biceps. **Just out of curiosity, how did you hear about biceps?** 

FYI: This issue will be closed upon releasing our most recent version. I will also provide the command for the installation. Thanks.

**Comment by thatch** [comment]
I'm doing an analysis of what builds on pypi, and started with projects updated in the last year.  I've built about 86k projects in a sandbox so far, and yours is one of them.

**Comment by robraddi** [comment]
This issue should be resolved with [new version](https://pypi.org/project/biceps/). Thanks.
